[versions]
morphe-patcher = "1.1.1"
#noinspection GradleDependency
smali = "b6365a84f4"
gson = "2.13.2"
annotation = "1.9.1"
appcompat = "1.7.1"

[libraries]
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

[plugins]
android-library = { id = "com.android.library" }
